### ISSUE TITLE
User roles & capabilities are exponentially duplicated

### ISSUE THREAD

**Issue by joeljv91** [globalis-ms/multisite-clone-duplicator#62]
When we are duplicating sites and I looked in usermeta table I advice data is duplicating exponentially for each duplication.

Example:

Duplicate Main site to site2:

y5dwg245el_2_capabilities

Duplicate Main site to site3:

y5dwg245el_3_capabilities
y5dwg245el_3_2_capabilities

Duplicate Main site to site4:

y5dwg245el_4_capabilities
y5dwg245el_4_3_capabilities
y5dwg245el_4_3_2_capabilities

If you need more info, let me know.

**Comment by pierre-dargham** [comment]
Thank you for reporting this bug,

We will run some tests and if we find what caused the issue, we will release a fix in next version 1.5.0.

Bests regards,

Pierre
