### ISSUE TITLE
Error with log path validation (valid_unix_dir_path)

### ISSUE THREAD

**Issue by herewithme** [globalis-ms/multisite-clone-duplicator#71]
The regular express seems incorrect and does not support the points in the WP installation paths.

Function : valid_unix_dir_path()
```
var_dump($bool, $reg, $path);

int(0) 
string(27) "/^(\/([a-z0-9+$_-])+)*\/?$/" 
string(111) "/var/www/sites/preprod/www.mywebsite.com/current/wp-content/uploads/multisite-clone-duplicator-logs/"
```

**Comment by herewithme** [comment]
Perhaps a candidate:
https://stackoverflow.com/questions/6416065/c-sharp-regex-for-file-paths-e-g-c-test-test-exe/42036026#42036026

**Comment by davddo** [comment]
#72
